In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [12]:
from sklearn.model_selection import train_test_split

X = df['Message']
y = df['spam']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [14]:
X_train.shape

(4457,)

In [15]:
X_test.shape

(1115,)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train.values)

In [18]:
cv.vocabulary_

{'lol': 4153,
 'nah': 4622,
 'wasn': 7316,
 'too': 6901,
 'bad': 1182,
 'thanks': 6728,
 'its': 3748,
 'good': 3157,
 'to': 6860,
 'home': 3449,
 'but': 1560,
 'been': 1274,
 'quite': 5465,
 'reality': 5539,
 'check': 1739,
 'hows': 3503,
 'ur': 7125,
 'day': 2160,
 'did': 2277,
 'do': 2351,
 'anything': 990,
 'with': 7468,
 'website': 7354,
 'reverse': 5703,
 'is': 3729,
 'cheating': 1737,
 'that': 6735,
 'not': 4769,
 'mathematics': 4338,
 'yeh': 7605,
 'indians': 3647,
 'was': 7314,
 'nice': 4707,
 'tho': 6785,
 'it': 3741,
 'kane': 3876,
 'me': 4358,
 'off': 4834,
 'bit': 1349,
 'he': 3344,
 'we': 7340,
 'shud': 6069,
 'go': 3133,
 'out': 4944,
 'drink': 2430,
 'sometime': 6239,
 'soon': 6253,
 'mite': 4468,
 'hav': 3330,
 'da': 2123,
 'works': 7521,
 'laugh': 4004,
 'love': 4195,
 'pete': 5102,
 '09066362231': 225,
 'urgent': 7129,
 'your': 7634,
 'mobile': 4492,
 'no': 4733,
 '07xxxxxxxxx': 42,
 'won': 7498,
 '000': 1,
 'bonus': 1405,
 'caller': 1596,
 'prize': 5354,
 'on': 4874,
 '02': 8,
 '06': 18,
 '03': 13,
 'this': 6778,
 'the': 6739,
 '2nd': 402,
 'attempt': 1114,
 'reach': 5524,
 'you': 7629,
 'call': 1590,
 'asap': 1074,
 'chinatown': 1773,
 'got': 3175,
 'porridge': 5243,
 'claypot': 1816,
 'rice': 5711,
 'yam': 7592,
 'cake': 1583,
 'fishhead': 2855,
 'beehoon': 1273,
 'either': 2536,
 'eat': 2499,
 'cheap': 1734,
 'den': 2220,
 'cafe': 1581,
 'tok': 6874,
 'or': 4913,
 'nydc': 4813,
 'somethin': 6237,
 'watching': 7324,
 'tv': 7013,
 'lor': 4174,
 'gud': 3242,
 'mrng': 4559,
 'dear': 2171,
 'yeah': 7601,
 'jay': 3783,
 'sort': 6262,
 'of': 4832,
 'fucking': 3010,
 'retard': 5692,
 'she': 6004,
 'borderline': 1417,
 'whatever': 7400,
 'buzzzz': 1569,
 'grins': 3221,
 'buzz': 1568,
 'ass': 1092,
 'chest': 1756,
 'cock': 1860,
 'where': 7407,
 'keep': 3890,
 'phone': 5115,
 'vibrator': 7199,
 'feel': 2784,
 'shake': 5990,
 'friendship': 2987,
 'poem': 5216,
 'near': 4656,
 'can': 1612,
 'hear': 3355,
 'dont': 2387,
 'get': 3093,
 'fear': 2776,
 'live': 4120,
 'cheer': 1746,
 'more': 4528,
 'tear': 6664,
 'always': 920,
 'my': 4608,
 'ni8': 4705,
 'were': 7385,
 'somewhere': 6242,
 'fredericksburg': 2963,
 'seriously': 5958,
 'tell': 6679,
 'her': 3387,
 'those': 6786,
 'exact': 2670,
 'words': 7514,
 'right': 5715,
 'now': 4784,
 'wishing': 7464,
 'beautiful': 1259,
 'each': 2484,
 'moment': 4510,
 'revealing': 5702,
 'even': 2642,
 'things': 6769,
 'smiling': 6185,
 'enjoy': 2579,
 'hurry': 3538,
 'big': 1330,
 'butt': 1561,
 'hang': 3298,
 'up': 7107,
 'last': 3996,
 'if': 3581,
 'have': 3334,
 'food': 2914,
 'done': 2385,
 'and': 951,
 'starving': 6388,
 'don': 2383,
 'ask': 1082,
 'what': 7399,
 'cooked': 1987,
 'congratulations': 1950,
 'claim': 1806,
 'vip': 7220,
 'row': 5762,
 'tickets': 6816,
 'blu': 1386,
 'in': 3623,
 'concert': 1934,
 'november': 4783,
 'gift': 3104,
 'guaranteed': 3240,
 '09061104276': 184,
 'ts': 6990,
 'cs': 2073,
 'www': 7563,
 'smsco': 6194,
 'net': 4682,
 'cost': 2006,
 '75max': 609,
 'just': 3858,
 'forced': 2922,
 'myself': 4613,
 'slice': 6156,
 'really': 5543,
 'hungry': 3532,
 'sucks': 6503,
 'mark': 4315,
 'getting': 3099,
 'worried': 7525,
 'knows': 3941,
 'sick': 6078,
 'when': 7404,
 'turn': 7008,
 'down': 2409,
 'pizza': 5155,
 'change': 1709,
 'windows': 7445,
 'logoff': 4149,
 'sound': 6271,
 'please': 5178,
 'text': 6711,
 'anymore': 985,
 'nothing': 4774,
 'else': 2546,
 'say': 5857,
 'sorry': 6261,
 'lot': 4182,
 'friend': 2984,
 'stuff': 6477,
 'about': 755,
 'talk': 6621,
 'actual': 793,
 'guy': 3261,
 'who': 7419,
 'wants': 7304,
 'buy': 1565,
 'somebody': 6230,
 'set': 5964,
 'play': 5171,
 'hold': 3441,
 'em': 2549,
 'using': 7151,
 'eve': 2640,
 'online': 4884,
 'spacebucks': 6285,
 'afternoon': 842,
 'sunshine': 6537,
 'how': 3498,
 'dawns': 2159,
 'are': 1037,
 'refreshed': 5594,
 'happy': 3312,
 'be': 1253,
 'alive': 898,
 'breathe': 1480,
 'air': 870,
 'smile': 6182,
 'think': 6770,
 'as': 1072,
 'daddy': 2128,
 'will': 7439,
 'make': 4285,
 'scream': 5885,
 'pleasure': 5181,
 'am': 922,
 'going': 3146,
 'slap': 6146,
 'dick': 2274,
 'sir': 6114,
 'send': 5938,
 'group': 3227,
 'mail': 4278,
 'mmm': 4479,
 'thats': 6738,
 'better': 1313,
 'roast': 5734,
 'had': 3272,
 'few': 2799,
 'drinks': 2433,
 'indian': 3646,
 'said': 5812,
 'wrong': 7548,
 'de': 2166,
 'mm': 4478,
 'umma': 7049,
 'vava': 7178,
 'also': 915,
 'come': 1889,
 'him': 3411,
 'later': 4001,
 'together': 6871,
 'rats': 5512,
 'hey': 3397,
 'ever': 2647,
 'vote': 7246,
 'for': 2920,
 'next': 4703,
 'themes': 6750,
 'ok': 4855,
 'pls': 5186,
 'all': 899,
 'know': 3939,
 'relatives': 5612,
 'coming': 1895,
 'deliver': 2212,
 'here': 3388,
 'costs': 2009,
 'risks': 5728,
 'benefits': 1303,
 've': 7181,
 'barred': 1213,
 'from': 2999,
 'stores': 6442,
 'life': 4069,
 'twat': 7014,
 'orange': 4917,
 'dungerees': 2471,
 'came': 1607,
 'asked': 1084,
 'wanted': 7302,
 'decking': 2185,
 'so': 6213,
 'first': 2854,
 'punch': 5425,
 'win': 7441,
 '100': 251,
 'music': 4598,
 'vouchers': 7250,
 'every': 2648,
 'week': 7362,
 'starting': 6385,
 'txt': 7023,
 'word': 7513,
 'draw': 2422,
 '87066': 682,
 'tscs': 6992,
 'idew': 3575,
 'com': 1883,
 'skillgame': 6135,
 '1winaweek': 337,
 'age16': 850,
 '150ppermesssubscription': 301,
 'ic': 3560,
 'should': 6048,
 'doors': 2395,
 'yo': 7624,
 'shopping': 6038,
 'them': 6749,
 'raining': 5484,
 'mah': 4274,
 'hard': 3313,
 'leave': 4033,
 'orchard': 4920,
 'voucher': 7249,
 'holder': 3442,
 'weeks': 7366,
 'offer': 4836,
 'at': 1104,
 'pc': 5054,
 'http': 3514,
 'tlp': 6850,
 'co': 1853,
 'uk': 7047,
 'reward': 5706,
 'apply': 1015,
 'kallis': 3873,
 'ready': 5534,
 'bat': 1225,
 'innings': 3666,
 'baaaaabe': 1171,
 'misss': 4462,
 'youuuuu': 7640,
 'teach': 6658,
 'class': 1814,
 'hope': 3466,
 'having': 3340,
 'checking': 1743,
 'like': 4081,
 'pa': 4975,
 'able': 753,
 'height': 3367,
 'oh': 4850,
 'shit': 6024,
 'situation': 6125,
 'throws': 6803,
 'luv': 4228,
 'letter': 4058,
 'gal': 3040,
 'falls': 2741,
 'brothers': 1511,
 'head': 3345,
 'whos': 7422,
 'gay': 3065,
 'yourself': 7639,
 'slowly': 6170,
 'becomes': 1265,
 'habit': 3271,
 'amp': 938,
 'finally': 2832,
 'part': 5016,
 'follow': 2905,
 'morning': 4532,
 'wont': 7505,
 'once': 4878,
 'fishrman': 2856,
 'woke': 7493,
 'early': 2488,
 'very': 7193,
 'dark': 2142,
 'waited': 7277,
 'while': 7414,
 'found': 2947,
 'sack': 5801,
 'ful': 3015,
 'stones': 6433,
 'strtd': 6466,
 'throwin': 6801,
 'thm': 6781,
 'in2': 3624,
 'sea': 5894,
 'pass': 5025,
 'time': 6827,
 'atlast': 1108,
 'jus': 3857,
 '1stone': 333,
 'sun': 6528,
 'rose': 5756,
 'tht': 6806,
 'nt': 4791,
 'diamonds': 2272,
 'moral': 4527,
 'wake': 7280,
 'night': 4714,
 'nope': 4754,
 'meanwhile': 4367,
 'greet': 3217,
 'horrible': 3479,
 'macs': 4259,
 'until': 7105,
 'forgot': 2933,
 'abt': 760,
 'already': 912,
 'rite': 5729,
 'take': 6614,
 'long': 4159,
 'reply': 5652,
 'thk': 6779,
 'toot': 6904,
 'than': 6724,
 'b4': 1167,
 'prepared': 5318,
 'wat': 7321,
 'shall': 5991,
 'goodmorning': 3162,
 'grandfather': 3197,
 'expired': 2697,
 'today': 6867,
 'would': 7535,
 'great': 3211,
 'll': 4128,
 'guild': 3254,
 'could': 2013,
 'meet': 4377,
 'bristol': 1498,
 'road': 5732,
 'touch': 6923,
 'over': 4957,
 'weekend': 7363,
 'our': 4941,
 'plans': 5168,
 'flight': 2877,
 'message': 4406,
 'castor': 1666,
 'need': 4667,
 'see': 5912,
 'something': 6238,
 'haha': 3274,
 'okay': 4856,
 'leh': 4043,
 'adult': 817,
 '18': 314,
 'content': 1967,
 'video': 7204,
 'shortly': 6045,
 'vl': 7236,
 'chat': 1729,
 're': 5523,
 'still': 6423,
 'maybe': 4353,
 'credit': 2052,
 'card': 1633,
 'gas': 3059,
 'back': 1180,
 'told': 6878,
 'yes': 7613,
 'any': 983,
 'plm': 5184,
 'office': 4839,
 'ill': 3594,
 'then': 6752,
 'doing': 2374,
 'srs': 6360,
 'model': 4502,
 'id': 3568,
 'secret': 5903,
 'admirer': 809,
 'looking': 4167,
 'contact': 1963,
 'find': 2835,
 'they': 6763,
 'reveal': 5700,
 'thinks': 6774,
 'special': 6297,
 '09065171142': 215,
 'stopsms': 6440,
 '08718727870150ppm': 144,
 'ya': 7588,
 'referin': 5588,
 'mei': 4384,
 'ex': 2669,
 'ah': 859,
 'waitin': 7278,
 'treat': 6959,
 'shld': 6029,
 'rich': 5712,
 'liao': 4061,
 'gd': 3072,
 'dun': 2470,
 'work': 7515,
 'frm': 2991,
 'tmr': 6854,
 'onwards': 4889,
 'hi': 3401,
 'email': 2550,
 'address': 802,
 'has': 3321,
 'changed': 1710,
 'movies': 4552,
 'laptop': 3989,
 'yun': 7649,
 'buying': 1566,
 'school': 5870,
 '2000': 343,
 'plus': 5190,
 'only': 4885,
 'finish': 2841,
 'bathing': 1230,
 'mind': 4434,
 'into': 3697,
 'bedroom': 1271,
 'minute': 4447,
 'sed': 5911,
 'sexy': 5977,
 'mood': 4525,
 'minuts': 4449,
 'latr': 4003,
 'wid': 7429,
 'wife': 7432,
 'telling': 6680,
 'incident': 3628,
 'babe': 1172,
 'advice': 822,
 'working': 7519,
 'eyes': 2716,
 'philosophy': 5112,
 'free': 2964,
 'ignorant': 3585,
 'tessy': 6704,
 'favor': 2771,
 'convey': 1981,
 'birthday': 1347,
 'wishes': 7462,
 'nimya': 4723,
 'dnt': 2350,
 'forget': 2928,
 'shijas': 6015,
 'want': 7300,
 'explicit': 2701,
 'sex': 5973,
 '30': 420,
 'secs': 5907,
 'ring': 5719,
 '02073162414': 11,
 '20p': 350,
 'min': 4432,
 'wearing': 7346,
 '08712402902': 102,
 'immediately': 3607,
 'there': 6757,
 'an': 946,
 'waiting': 7279,
 'heehee': 3366,
 'funny': 3026,
 'cal': 1585,
 'meeting': 4379,
 'multiply': 4585,
 'numbers': 4799,
 'independently': 3643,
 'count': 2016,
 'decimal': 2182,
 'points': 5218,
 'division': 2340,
 'push': 5435,
 'places': 5160,
 'showed': 6055,
 'sad': 5804,
 'story': 6444,
 'man': 4294,
 'wish': 7460,
 'parents': 5010,
 'kids': 3913,
 'went': 7382,
 'colleagues': 1872,
 'wana': 7297,
 'project': 5379,
 'after': 840,
 'fact': 2722,
 'money': 4516,
 'raise': 5485,
 'buns': 1545,
 'adore': 812,
 'loverboy': 4201,
 'remember': 5623,
 'thank': 6727,
 'sister': 6117,
 'law': 4011,
 'meatballs': 4370,
 'sure': 6555,
 'neighbors': 4677,
 'didnt': 2279,
 'pick': 5128,
 'hmm': 3430,
 'stay': 6395,
 'hour': 3491,
 'cos': 2004,
 'eye': 2714,
 'sore': 6259,
 'solve': 6226,
 'case': 1659,
 'murdered': 4594,
 'lt': 4216,
 'gt': 3236,
 'his': 3418,
 'called': 1595,
 'police': 5222,
 'questioned': 5459,
 'everyone': 2653,
 'sleeping': 6150,
 'murder': 4593,
 'took': 6902,
 'place': 5157,
 'cook': 1986,
 'cooking': 1989,
 'gardener': 3055,
 'picking': 5130,
 'vegetables': 7183,
 'house': 3494,
 'maid': 4277,
 'post': 5260,
 'children': 1768,
 'neighbour': 4678,
 'marriage': 4321,
 'arrested': 1061,
 'murderer': 4595,
 'reason': 5548,
 'brilliant': 1492,
 'give': 3117,
 'much': 4578,
 'fun': 3020,
 'without': 7471,
 'tomorrow': 6888,
 'jess': 3804,
 'played': 5172,
 'smash': 6177,
 'bros': 1507,
 'religiously': 5618,
 'accidentally': 770,
 'left': 4038,
 'silent': 6091,
 'didn': 2278,
 'til': 6824,
 'pretty': 5335,
 'best': 1307,
 'scenario': 5867,
 'awesome': 1159,
 '8th': 712,
 'usf': 7149,
 'some': 6228,
 'tonight': 6896,
 'drinkin': 2431,
 'dinner': 2303,
 'sch': 5868,
 'neva': 4691,
 '1st': 330,
 'dat': 2151,
 'leaving': 4035,
 'shanghai': 5995,
 '21st': 353,
 'instead': 3679,
 'haf': 3273,
 'cya': 2120,
 'fast': 2760,
 'asleep': 1089,
 'care': 1637,
 'link': 4100,
 'picture': 5134,
 'sent': 5948,
 'use': 7143,
 'alto18': 918,
 'wave': 7333,
 'asp': 1090,
 '44345': 491,
 'fantasy': 2754,
 'football': 2918,
 'sky': 6141,
 'gamestar': 3046,
 'active': 790,
 '250k': 365,
 'dream': 2424,
 'team': 6662,
 'scoring': 5878,
 'starts': 6386,
 'saturday': 5848,
 'register': 5603,
 'opt': 4907,
 '88088': 693,
 '09066612661': 234,
 'landline': 3979,
 'complimentary': 1918,
 'lux': 4231,
 'costa': 2007,
 'del': 2206,
 'sol': 6222,
 'holiday': 3444,
 '1000': 252,
 'cash': 1660,
 'await': 1153,
 'collection': 1876,
 'ppm': 5283,
 '150': 296,
 'sae': 5805,
 'james': 3769,
 '28': 372,
 'eh74rr': 2531,
 'depends': 2230,
 'quality': 5452,
 'type': 7034,
 'boye': 1453,
 'faded': 2724,
 'glory': 3126,
 'ralphs': 5495,
 'though': 6788,
 'friday': 2981,
 'cant': 1624,
 'wait': 7276,
 'dunno': 2472,
 'wot': 7532,
 'hell': 3370,
 'im': 3598,
 'gonna': 3155,
 'another': 970,
 'become': 1264,
 'slob': 6165,
 'sat': 5842,
 'cool': 1990,
 'budget': 1532,
 'available': 1141,
 'unsold': 7099,
 'players': 5174,
 'base': 1217,
 'rate': 5508,
 'us': 7140,
 'again': 846,
 'matthew': 4345,
 '09063440451': 202,
 'tenerife': 6692,
 'ppm150': 5284,
 'box334': 1442,
 'sk38xh': 6132,
 'slave': 6147,
 'shell': 6009,
 'unconsciously': 7063,
 'avoiding': 1151,
 'making': 4288,
 'unhappy': 7079,
 'pain': 4985,
 'trouble': 6974,
 'pours': 5276,
 'rain': 5483,
 'sum1': 6522,
 'hurts': 3541,
 'becoz': 1266,
 'someone': 6232,
 'loves': 4203,
 'pay': 5044,
 'rent': 5639,
 'bank': 1202,
 'authorise': 1135,
 'payment': 5050,
 'esplanade': 2625,
 'giving': 3120,
 'lift': 4074,
 'car': 1632,
 'aren': 1039,
 'hours': 3493,
 'imma': 3605,
 'flip': 2880,
 'packing': 4979,
 'let': 4056,
 'room': 5750,
 'most': 4536,
 'people': 5072,
 'town': 6929,
 'nordstrom': 4758,
 'being': 1289,
 'ripped': 5725,
 'clubmoby': 1843,
 '08717509990': 131,
 'poly': 5224,
 'true': 6979,
 'pix': 5153,
 'ringtones': 5724,
 'games': 3045,
 'six': 6128,
 'downloads': 2412,
 'new': 4695,
 'year': 7602,
 'seeing': 5914,
 'weird': 7369,
 'bein': 1288,
 'woah': 7491,
 'realising': 5538,
 'actually': 794,
 'reasonable': 5549,
 'carlos': 1649,
 'anybody': 984,
 'chip': 1779,
 'hai': 3276,
 'ana': 947,
 'tomarrow': 6883,
 'sathy': 5843,
 'rto': 5775,
 'staff': 6367,
 'placement': 5159,
 'training': 6940,
 'amrita': 941,
 'college': 1878,
 'hostel': 3485,
 'sleep': 6148,
 'plz': 5192,
 'before': 1279,
 'hrishi': 3510,
 'okie': 4860,
 'thanx': 6732,
 'one': 4880,
 'interested': 3687,
 'may': 4351,
 'business': 1557,
 'plan': 5162,
 'consensus': 1956,
 'pics': 5132,
 'bigger': 1331,
 'nokia': 4743,
 '3510i': 442,
 'colour': 1880,
 'delivered': 2213,
 '200': 342,
 'minutes': 4448,
 'camcorder': 1606,
 '08000930705': 48,
 'diff': 2284,
 'guess': 3246,
 'round': 5758,
 'month': 4522,
 'kotees': 3951,
 'pray': 5301,
 'remove': 5633,
 'teeth': 6673,
 'painful': 4986,
 'maintaining': 4283,
 'other': 4934,
 'na': 4618,
 'days': 2161,
 'euro2004': 2635,
 'kickoff': 3909,
 'kept': 3897,
 'informed': 3658,
 'latest': 4002,
 'news': 4700,
 'results': 5689,
 'daily': 2131,
 'unsubscribe': 7102,
 'euro': 2634,
 'stop': 6434,
 '83222': 656,
 'ain': 868,
 'answerin': 975,
 'sleepy': 6154,
 'movie': 4551,
 'hourish': 3492,
 'eighth': 2533,
 'try': 6987,
 'mate': 4335,
 'thing': 6768,
 'past': 5033,
 'din': 2297,
 '420': 481,
 'job': 3817,
 'wipro': 7456,
 'years': 7603,
 'little': 4119,
 'meds': 4375,
 'die': 2280,
 'hooch': 3460,
 'walk': 7283,
 'toaday': 6862,
 'fell': 2792,
 'splat': 6326,
 'grazed': 3209,
 'knees': 3935,
 'everything': 2656,
 'stayed': 6396,
 'per': 5074,
 'request': 5657,
 'maangalyam': 4250,
 'alaipayuthe': 884,
 'callertune': 1598,
 'callers': 1597,
 'press': 5331,
 'copy': 1996,
 'friends': 2985,
 'accept': 767,
 'brother': 1510,
 'lover': 4200,
 'dear1': 2172,
 'best1': 1308,
 'clos1': 1830,
 'lvblefrnd': 4234,
 'jstfrnd': 3845,
 'cutefrnd': 2113,
 'lifpartnr': 4073,
 'belovd': 1297,
 'swtheart': 6592,
 'bstfrnd': 1524,
 'rply': 5768,
 'means': 4365,
 'enemy': 2571,
 'fine': 2838,
 'absolutly': 759,
 'lick': 4064,
 'pussy': 5438,
 'stayin': 6397,
 'extra': 2710,
 'wed': 7355,
 'rugby': 5781,
 '83039': 652,
 '62735': 573,
 '450': 494,
 'break': 1474,
 'accommodationvouchers': 772,
 'terms': 6697,
 'conditions': 1937,
 'mustprovide': 4602,
 'number': 4798,
 'which': 7413,
 '15541': 308,
 'ard': 1036,
 'oclock': 4828,
 'mine': 4435,
 'bash': 1219,
 'flat': 2870,
 'tee': 6671,
 'hee': 3365,
 'lecture': 4037,
 'cheery': 1749,
 'bye': 1576,
 'al': 882,
 'does': 2362,
 'moan': 4489,
 'thin': 6767,
 'goes': 3141,
 'fault': 2768,
 'arguments': 1048,
 'fed': 2781,
 'himso': 3413,
 'bother': 1427,
 '2go': 388,
 'xx': 7576,
 'doubt': 2406,
 'handle': 3293,
 'times': 6828,
 'private': 5351,
 '2003': 344,
 'account': 775,
 'statement': 6392,
 '07815296484': 36,
 'shows': 6062,
 '800': 627,
 'un': 7053,
 'redeemed': 5582,
 '08718738001': 147,
 'identifier': 3574,
 'code': 1862,
 '41782': 480,
 'expires': 2698,
 '11': 263,
 '04': 14,
 ...}

In [28]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [29]:
X_test_cv = cv.transform(X_test)

In [32]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.98      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [33]:
emails = [
    "Hey, I was wondering if you would like to grab lunch sometime this week?",
    "Congratulations! You've won a $1,000 Walmart gift card. Click here to claim your prize.",
]

In [35]:
emails_cv = cv.transform(emails)
model.predict(emails_cv)

array([0, 1])

using pipeline

In [36]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb_model', MultinomialNB())
])

In [37]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('nb_model', MultinomialNB())])

In [38]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.98      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115