In [ ]:
!pip install gensim
!pip install python-Levenshtein

Collecting gensim
  Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.3 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 54.0 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 71.4 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 14.8 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.2
    Uninstalling scipy-1.16.2:
      Successfully uninstalled scipy-1.16.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

Collecting python-Levenshtein
  Downloading python_levenshtein-0.27.1-py3-none-any.whl.metadata (3.7 kB)
Collecting Levenshtein==0.27.1 (from python-Levenshtein)
  Downloading levenshtein-0.27.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.1->python-Levenshtein)
  Downloading rapidfuzz-3.14.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
^C

In [1]:
import gensim
import pandas as pd

In [3]:
df = pd.read_csv('/content/TestReviews.csv')

In [9]:
df.head()

                                              review  class
0  Fantastic spot for an even or a quite cocktail...      1
1  Love, love, love the calamari. It's so good an...      1
2  Love this place. Stiff martinis and cocktails,...      1
3  It's everything a great cocktail bar should be...      1
4  I came here before a pirates game, so it was a...      1

In [4]:
review = df.review.apply(gensim.utils.simple_preprocess)

In [5]:
review

0       [fantastic, spot, for, an, even, or, quite, co...
1       [love, love, love, the, calamari, it, so, good...
2       [love, this, place, stiff, martinis, and, cock...
3       [it, everything, great, cocktail, bar, should,...
4       [came, here, before, pirates, game, so, it, wa...
                              ...
4316    [my, wife, and, caught, this, show, at, the, g...
4317    [this, was, the, dumbest, show, we, have, ever...
4318    [my, girlfriend, and, went, to, this, show, it...
4319    [the, restrooms, looked, like, after, an, bomb...
4320    [have, been, going, to, the, pennsylvania, mac...
Name: review, Length: 4321, dtype: object

training the w2c model

In [7]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    workers = 4
)

build vocabulary

In [8]:
model.build_vocab(review, progress_per = 1000)

train the w2v model

In [9]:
model.train(review, total_examples = model.corpus_count, epochs = model.epochs)

(1925399, 2565950)

find similar words and similarity

In [10]:
model.wv.most_similar('bad')

[('sad', 0.8844413161277771),
 ('such', 0.882982075214386),
 ('suspect', 0.8782625198364258),
 ('replacing', 0.8773843050003052),
 ('overall', 0.8724818229675293),
 ('albeit', 0.8685306310653687),
 ('desire', 0.8676011562347412),
 ('craving', 0.8670350909233093),
 ('disappointed', 0.8636427521705627),
 ('write', 0.8609428405761719)]

In [11]:
model.wv.similarity(w1="good", w2="great")

0.8155735

In [12]:
model.wv.similarity(w1="slow", w2="steady")

0.68333066